### ISSUE TITLE
Send feedback to other process if protocol is interrupted due to error

### ISSUE THREAD

**Issue by emysliwietz** [emysliwietz/hardware_security#14]
If e.g. the card and the auto talk and the card enters an errorState and returns, it might be nice to inform the auto instead of ghosting it

**Comment by AVanVeen** [comment]
Half done.
Card to terminal/Auto, all done.
Terminal/Auto -> Card - partially done. Something still needs to be send to card and that needs to be handled. Not sure how yet

**Comment by emysliwietz** [comment]
We now have a relatively nice way to do this (7df10026a591f9a9eb580b22ff1532881ca96257):

On the Terminal side, call
`sendErrorAPDU(INS_OF_CURRENT_PROTOCOL, ERROR_CODE);`
where `INS_OF_CURRENT_PROTOCOL` is just the normal old INS code we're using, like `INSERT_START` and the `ERROR_CODE` is  defined in Communicator.

On the Smartcard side, every method now has an `onError` error handler that gets called whenever an error in the corresponding method occured. The parameter `sw` is the `ERROR_CODE` send by the terminal. For a handling example, see `initOnError` in Smartcard.

I didn't implement any actual error handling yet
