### ISSUE TITLE
usages of memCpy might need error handling

### ISSUE THREAD

**Issue by AVanVeen** [emysliwietz/hardware_security#31]
If the memCpy is out of bounds, then the program will crash. This can happen for example if the card does not have a car loaded on it (easy attack to crash our system).

To test:
- Insert card
- Choose Auto
- boom crash

**Comment by emysliwietz** [comment]
memCpy itself works exactly as specified, it already throws all the relevant runtime errors like IndexOutOfBoundsException, etc. If anything, that should be checked on usage
