### ISSUE TITLE
Database needs to be cleared at start of program

### ISSUE THREAD

**Issue by MaJoEi** [emysliwietz/hardware_security#33]
We only create one auto, but there are multiple autos in the database. We removed the placeholder that the auto sends its certificate to the card, but that would break our security assumptions that the card is verified since it knows the auto's credentials beforehand. The program crashes if there are multiple autos in the DB since then the database seems to send the data of an entirely different auto to the database. If you clear the database beforehand, this does not happen

**Comment by MaJoEi** [comment]
To be specific, only the auto table needs to be empty, the other tables don't really matter here. This is just a limitation of our implementation, in actual practice, this would not be an issue

**Comment by MaJoEi** [comment]
Alternatively: Make sure, that the right autoID gets assigned to the card (in that case, the table would not need to be cleared anymore)

**Comment by AVanVeen** [comment]
Table cleared for now. Will look into alternative later
