### ISSUE TITLE
BlockCard (Reception): request.equals if statement never fulfilled

### ISSUE THREAD

**Issue by AVanVeen** [emysliwietz/hardware_security#34]
if (!request.equals(new String(cardID) + " has been removed from cards.")) will never be fulfilled, thus causing the program to always crash.
msgBuf in database seems to be fine. request seems to be a pointer though. 
We can't figure it out.

**Comment by MaJoEi** [comment]
Could it be, that there is a toHexString(cardID) instead of a new String(cardID) on the other side? That seems like the most likely cause of error. Or it's an instance of a race condition with the stack (which is less likely)

**Comment by MaJoEi** [comment]
Issue was, a) that the it was indeed toHexString on the other side (changed that) and you missed the last 2 bytes while memCpy-ing.
