### ISSUE TITLE
Finishing up

### ISSUE THREAD

**Issue by emysliwietz** [emysliwietz/hardware_security#36]
- [x] Close all issues
- [x] merge dev into main
- [x] delete all branches except for main
- [x] Update design document
- [x] upload PDF and .tex to GitHub for reference
- [x] Hand in

--- impossible tasks, never to be completed
Create JAR (regarded as impossible)
Add JAR to releases

**Comment by AVanVeen** [comment]
Alesssandra also deems a JAR as impossible
