### ISSUE TITLE
Success message

### ISSUE THREAD

**Issue by AVanVeen** [emysliwietz/hardware_security#7]
A success message or some form of communication should be done in all protocols. 
Please check for all protocols (Overleaf document should be adjusted) if they are fixed, and if not, fix it.

Checklist
- [x]  Protocol 1
- [x]  Protocol 2
- [x]  Protocol 3
- [x]  Protocol 4
- [x]  Protocol 5
- [x]  Protocol 6

**Comment by MaJoEi** [comment]
Just send signed(0xFFFF)

**Comment by emysliwietz** [comment]
add a successState(msg) similar to the errorState(msg) for use in GUI later on

**Comment by MaJoEi** [comment]
Already solved the issue and updated Latex document
