### ISSUE TITLE
SQLite Certificate Storage Database

### ISSUE THREAD

**Issue by emysliwietz** [emysliwietz/hardware_security#8]

**Comment by AVanVeen** [comment]
Whoever gets to it first

**Comment by AVanVeen** [comment]
SQLite database should probably exist out of 3 tables:
1. Terminals
2. Autos
3. Smartcard

Each table stores the id of the object, the public key, and the certificate.
Database should have a certificate/private/public key of itself stores somewhere as well.
Further, table 2 and 3 need to have a fourth column that says autoid (if it is the card) or cardid (if auto table) which is default set to null and will be filled in if there is a auto-card assignment
